/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pravin
 */
public class MainMenu extends javax.swing.JFrame {
     Connection conn = null;
     ResultSet rs = null;
     PreparedStatement pst = null;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        conn = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        
        lbl_emp.setText(String.valueOf(emp.empname).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Logged As:");

        lbl_emp.setText("emp");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Employee manager");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Payment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Allowance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deduction");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Employee ");

        jMenuItem1.setText("Employee Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_emp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 249, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addGap(119, 119, 119))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_emp))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        login x = new login();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        addEmployee x= new  addEmployee();
        x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         deductions x= new  deductions();
        x.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Allowance x= new  Allowance();
        x.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        salary x= new  salary();
        x.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new java.io.File ("Employee report.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult==JFileChooser.APPROVE_OPTION){

            String filepath = dialog.getSelectedFile().getPath();
            try{

                String sql ="Select * from staff_information ";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
               
               

               

               

                Document myDocument= new Document();
                PdfWriter myWriter=PdfWriter.getInstance(myDocument , new FileOutputStream
(filepath));
               PdfPTable table=new PdfPTable(13);
                myDocument.open();
                float[] columnwidths = new float[]{3,8,7,5,5,9,8,9,6,6,6,8,8};
                table.setWidths(columnwidths);
                table.setWidthPercentage(100);
                myDocument.add(new Paragraph("EMPLOYEE LIST",FontFactory.getFont
(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                myDocument.add(new Paragraph(new Date().toString()));
                myDocument.add(new Paragraph("-----------------------------------------------------"));
                table.addCell(new Paragraph("id",FontFactory.getFont
(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                table.addCell(new Paragraph("first name",FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                table.addCell(new Paragraph("surname",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                table.addCell(new Paragraph("Date of birth",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                
               
               table.addCell(new Paragraph("Email",FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                
                
                table.addCell(new Paragraph("Telephone",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                table.addCell(new Paragraph("Department",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                table.addCell(new Paragraph("Salary",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               
            
                table.addCell(new Paragraph("Address",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               
               table.addCell(new Paragraph("Adress2",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph("Apartment",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph("post code",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
                table.addCell(new Paragraph("Job title",FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
              while(rs.next()){
              table.addCell(new Paragraph(rs.getString(1),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
              table.addCell(new Paragraph(rs.getString(2),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
              table.addCell(new Paragraph(rs.getString(3),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL))); 
               table.addCell(new Paragraph(rs.getString(4),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(5),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(6),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(7),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(8),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(9),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(10),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(11),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(12),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
               table.addCell(new Paragraph(rs.getString(13),FontFactory.getFont
(FontFactory.TIMES_ROMAN, 10, Font.NORMAL)));
              }
               
               myDocument.add(table);
                myDocument.add(new Paragraph("-----------------------------------------------------"));
                myDocument.close();
                JOptionPane.showMessageDialog(null, "Report was successfully generated");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
            
            
            
            
        }      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_emp;
    // End of variables declaration//GEN-END:variables
}
